//------------------------------------------------------------------------------
// <autogenerated>
//     This Oxygene source code was generated by a tool.
//     Oxygene Version: 4.0.23.741
//     Runtime Version: 4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

{$HIDE CW3}
{$HIDE PW12}

namespace EnterpriseLibraryWebApplication;

interface

type
    _Default = public partial class
    protected 
        var form1: System.Web.UI.HtmlControls.HtmlForm;
        var Label1: System.Web.UI.WebControls.Label;
end;

implementation

end.
